services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: datastorage
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pdf_builder_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/datastorage
      SPRING_DATASOURCE_USERNAME: pguser
      SPRING_DATASOURCE_PASSWORD: pgpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
